-- 仅查 blade 库关键 ACT_* 表的索引与外键（只读）
SELECT '===== blade 库关键表索引 =====' AS section;
SELECT TABLE_NAME, INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = 'blade'
  AND TABLE_NAME IN ('ACT_HI_PROCINST','ACT_RU_TASK','ACT_HI_TASKINST','ACT_RU_EXECUTION','ACT_RU_VARIABLE','ACT_HI_VARINST')
ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;

SELECT '===== blade 库 ACT_* 外键 =====' AS section;
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'blade' AND TABLE_NAME LIKE 'ACT\_%' AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

SELECT '===== blade 库关键表是否含 BUSINESS_STATUS_ =====' AS section;
SELECT TABLE_NAME, COUNT(*) AS has_business_status
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'blade' AND COLUMN_NAME = 'BUSINESS_STATUS_'
GROUP BY TABLE_NAME;

SELECT '===== blade 库 ACT_RU_TASK / ACT_HI_TASKINST 列清单 =====' AS section;
SELECT TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'blade' AND TABLE_NAME IN ('ACT_RU_TASK','ACT_HI_TASKINST','ACT_RU_EXECUTION','ACT_HI_PROCINST')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
