-- ACT_* 表现状分析：结构 / 数据量 / 索引 / 外键（只读，不做任何修改）
SELECT '===== 1. 表清单与数据量 =====' AS section;

SELECT TABLE_SCHEMA, TABLE_NAME, ENGINE, ROW_FORMAT,
       TABLE_ROWS,
       ROUND(DATA_LENGTH/1024/1024, 2)  AS data_mb,
       ROUND(INDEX_LENGTH/1024/1024, 2) AS idx_mb,
       ROUND((DATA_LENGTH+INDEX_LENGTH)/1024/1024, 2) AS total_mb,
       AUTO_INCREMENT
FROM information_schema.TABLES
WHERE TABLE_NAME LIKE 'ACT\_%'
ORDER BY TABLE_SCHEMA, TABLE_ROWS DESC;

SELECT '===== 2. 索引 =====' AS section;

SELECT TABLE_SCHEMA, TABLE_NAME, INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME
FROM information_schema.STATISTICS
WHERE TABLE_NAME LIKE 'ACT\_%'
ORDER BY TABLE_SCHEMA, TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;

SELECT '===== 3. 外键约束 =====' AS section;

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME,
       REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_NAME LIKE 'ACT\_%' AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY TABLE_SCHEMA, TABLE_NAME;

SELECT '===== 4. 关键表列结构（ACT_HI_PROCINST / ACT_RU_TASK / ACT_HI_TASKINST / ACT_RU_EXECUTION） =====' AS section;

SELECT TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, COLUMN_TYPE,
       IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA
FROM information_schema.COLUMNS
WHERE TABLE_NAME IN ('ACT_HI_PROCINST','ACT_RU_TASK','ACT_HI_TASKINST','ACT_RU_EXECUTION','ACT_RU_VARIABLE','ACT_HI_VARINST')
ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;
